apiVersion: v1
kind: ConfigMap
metadata:
  name: chrony-configmap
data:
  chrony.conf: |
    # from configmap
    pool time.cloudflare.com iburst maxsources 2
    pool time.google.com iburst maxsources 2
    makestep 0.1 4
    allow 0.0.0.0/0
